"""add is internal to actor and director

Revision ID: 2a918e13de2d
Revises: 7f20c0ea9d3b
Create Date: 2017-08-22 19:12:51.171952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a918e13de2d'
down_revision = '7f20c0ea9d3b'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('is_internal', sa.BOOLEAN(), nullable=True))
    op.add_column('director', sa.Column('is_internal', sa.BOOLEAN(), nullable=True))
    op.drop_column('movie', 'is_internal')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('is_internal', sa.BOOLEAN(), nullable=True))
    op.drop_column('director', 'is_internal')
    op.drop_column('actor', 'is_internal')
    ### end Alembic commands ###
