"""add forward_num to movie

Revision ID: 6578921bfe7c
Revises: 703d0a536840
Create Date: 2017-08-11 16:37:40.492737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6578921bfe7c'
down_revision = '703d0a536840'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('forward_num', sa.INTEGER(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'forward_num')
    ### end Alembic commands ###
