"""add is internal to actor and director

Revision ID: 7f20c0ea9d3b
Revises: 6578921bfe7c
Create Date: 2017-08-22 19:11:43.968894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f20c0ea9d3b'
down_revision = '6578921bfe7c'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('is_internal', sa.BOOLEAN(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'is_internal')
    ### end Alembic commands ###
